### ISSUE TITLE
Installation issue with aaPanel ?

### ISSUE THREAD

**Issue by matthew-asuncion** [rajwebconsulting/youtube-downloader-api-extension#4]
Please provide detailed documentation for installing this script on a Debian aaPanel server. Stepwise process
 
Thank You

**Comment by rustynail1984** [comment]
Just follow the instructions from the README

**Comment by matthew-asuncion** [comment]
> Just follow the instructions from the README

4. Build for production

After running command in domain directory: npm run build 
getting this error 

[https://prnt.sc/HfsWbFOkRS5R](https://prnt.sc/HfsWbFOkRS5R )

**Comment by matthew-asuncion** [comment]
I have installed it but API output is empty and blank page appears.

Demo: https://convertapi.dev

Please let me know possible issues and solution ?

**Comment by rustynail1984** [comment]
CORS issue.. Allow Domain in Admin Panel

**Comment by matthew-asuncion** [comment]
Allowed domain instead of IP works now. But API URLs directs to this 

URL: https://convertapi.dev/api/single/mp3?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DzvrMzRVtj1s

So, Its not working and empty page appears.

**Comment by matthew-asuncion** [comment]
Any solution ?

**Comment by rustynail1984** [comment]
check README
